version: "3"
services:
  auth:
    build: ./auth-service
    ports:
      - "3001:3001"

  user:
    build: ./user-service
    ports:
      - "3002:3002"

  order:
    build: ./order-service
    ports:
      - "3003:3003"