name: Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Containers
        run: docker-compose up -d --build

      - name: Wait for user-service
        run: |
          for i in {1..30}; do
            curl -s http://localhost:3002/health && echo "READY" && exit 0
            echo "Waiting..."
            sleep 2
          done
          echo "Service failed"
          docker-compose logs user-service
          exit 1

      - name: Install Swagger CLI
        run: npm install -g swagger-cli

      - name: Validate OpenAPI
        run: swagger-cli validate user-service/swagger.json

      - name: Run OWASP ZAP API Scan
        run: |
          docker run --network host -t owasp/zap2docker-stable \
          zap-api-scan.py -t http://localhost:3002/swagger.json -f openapi -r zap-report.html

      - name: Run Nuclei Scan
        run: |
          docker run --network host projectdiscovery/nuclei \
          -u http://localhost:3002 -o nuclei-report.txt

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            zap-report.html
            nuclei-report.txt